### ISSUE TITLE
DDoS attacks now :( & a question about docker

### ISSUE THREAD

**Issue by th3geek** [lukechilds/docker-electrumx#18]
Hi there,

Thanks again for all your help. I have a quick question about docker resource usage. I'm getting about 1000 connections per minute incoming from the DDoS attack and  y machine doesn't appear to be bottle necking anywhere so I'm wondering if its possible docker is limiting resources? I was told by default it did not limit resources, but I wondered if maybe you had changed a setting in that regard (an off chance, I know). Anyway I'm right now in the process of moving the server from a quad core laptop to a 32 core xeon with 64GB RAM (hyperV so actually 64 theoretical cores).  Hopefully the overkill of this server coupled with being on a fiber connection will help overpower the DDoSer.

That gets me to the main point of this message. E-X has been upgraded to limit resources based on IP address to help mitigate (and hopefully end) this DDoS. Think you could spare a few minutes to update to version 0.10.1 which was just released 18 hours ago? I've already sent a tip to get your attention, and you know how I roll after the fact ; )

edit:  Also, any idea why nothing is showing up under releases anymore?

**Comment by lukechilds** [comment]
Hey!

> I'm getting about 1000 connections per minute incoming from the DDoS attack and y machine doesn't appear to be bottle necking anywhere so I'm wondering if its possible docker is limiting resources? I was told by default it did not limit resources, but I wondered if maybe you had changed a setting in that regard (an off chance, I know).

This image doesn't change any settings, ElectrumX defaults to 1,000 max connections: https://electrumx.readthedocs.io/en/latest/environment.html#envvar-MAX_SESSIONS

You can set the `MAX_SESSIONS` environment variable to change that behaviour.

Have a read through the other options too, if you're increasing max connections you might wanna bump up some other limits with it.

>Think you could spare a few minutes to update to version 0.10.1 which was just released 18 hours ago?

Sure, that's done now, thanks for letting me know.

v1.10.1 is live on Docker Hub under both it's own tag and the latest tag.

To upgrade:

```
docker pull lukechilds/electrumx
```

>Also, any idea why nothing is showing up under releases anymore?

Due to the way the automated build process works with Docker Hub releases are done as git branches not tags so they don't show up as releases on GitHub. You can view them as tags on Docker Hub: https://hub.docker.com/r/lukechilds/electrumx/tags

**Comment by th3geek** [comment]
Thank so much!  really appreciate it!  so quick :

**Comment by lukechilds** [comment]
No worries, thanks for the tips ⚡️
